import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import Footer from "@/component/Footer/Footer";
import AuthContext from "@/contexts/AuthContext";
import { ToastContainer } from "react-toastify";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className={geistSans.variable}>
      {/* ✅ FIX 1: full height fix */}
      <body
        className={`${roboto.className} min-h-screen flex flex-col bg-[#F8FAFC] antialiased`}
      >
        <Navbar />

        {/* ✅ FIX 2: main flex-1 for sticky footer */}
        <main className="container mx-auto px-4 md:px-10 flex-1">
          <AuthContext>{children}</AuthContext>
        </main>

        <Footer />

        <ToastContainer />
      </body>
    </html>
  );
}
