import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar/Navbar";
import Footer from "@/component/Footer/Footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light" className={geistSans.variable}>
      <body
        className={`${roboto.className} min-h-full flex flex-col bg-[#F8FAFC] antialiased`}
      >
        <Navbar />
        <main className="container mx-auto px-10">{children}</main>
        <Footer className="mt-10"></Footer>
      </body>
    </html>
  );
}
